/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_happy_detection_DistanceTracker */

#ifndef _Included_edu_happy_detection_DistanceTracker
#define _Included_edu_happy_detection_DistanceTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_happy_detection_DistanceTracker
 * Method:    GetDistance
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_edu_happy_detection_DistanceTracker_GetDistance
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
